import Head from 'next/head';
import ComingSoon from '../../components/Home/ComingSoon';

function Soon() {
	return (
		<div>
			<Head>
				<title>Wait..</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<ComingSoon />
			</main>
		</div>
	);
}

export default Soon;
