import Head from 'next/head';
import AboutWeb3 from '../components/Home/AboutWeb3';
import BlockchainIndustries from '../components/Home/blockchainIndustries';
import ContactSection from '../components/Home/contactSection';
import Experience from '../components/Home/experience';
import About from '../components/Home/howWeWork';
import OurTeam from '../components/Home/ourTeam';
import ServicesSection from '../components/Home/servicesSection';
import Footer from '../components/shared/Footer';
import Hero from '../oldComponents/Hero';
import Technologies from '../components/Home/technologies';
import Navbar from '../components/shared/Navbar';
import Roadmap from '../components/Home/roadmap';

export default function Home() {
	return (
		<div className='overflow-x-hidden'>
			<Head>
				<title>chainhouse.io</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<Navbar />
				<Hero />
				<Technologies />
				<About />
				<Experience />
				<AboutWeb3 />
				<OurTeam />
				<Roadmap />
				<ServicesSection />
				<BlockchainIndustries />
				<ContactSection />
				<Footer />
			</main>
		</div>
	);
}
